In [11]:
def div_by_zero():
    return 5/0

try:
    div_by_zero()
except ZeroDivisionError as e:
    print("Handle run-time 'div by 0'error:", e)


Handle run-time 'div by 0'error: division by zero


In [12]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [13]:
import numpy as np
def vandermonde_matrix(ipvector,n,increasing=False):
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

print("----------------OUTPUT-----------------\n")

input_vector = np.array([1,2,3,4,5])
no_of_columns = 3

print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",no_of_columns,"\n")
print("Vandermonde matrix of the input array in decreasing order of powers:\n\n",vandermonde_matrix(input_vector,no_of_columns,False),"\n")
print("Vandermonde matrix of the input array in increasing order of powers:\n\n",vandermonde_matrix(input_vector,no_of_columns,True),"\n")

input_vector = np.array([1,2,4,6,8,10])
no_col_opmat = 5

print("---------------------------------------------------------------\n")
print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",no_of_columns,"\n")
print("Vandermonde matrix of the input array in decreasing order of powers:\n\n",vandermonde_matrix(input_vector,no_of_columns,False),"\n")
print("Vandermonde matrix of the input array in increasing order of powers:\n\n",vandermonde_matrix(input_vector,no_of_columns,True),"\n")

----------------OUTPUT-----------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vandermonde matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vandermonde matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

---------------------------------------------------------------

The input array is: [ 1  2  4  6  8 10] 

Number of columns in output matrix should be: 3 

Vandermonde matrix of the input array in decreasing order of powers:

 [[  1   1   1]
 [  4   2   1]
 [ 16   4   1]
 [ 36   6   1]
 [ 64   8   1]
 [100  10   1]] 

Vandermonde matrix of the input array in increasing order of powers:

 [[  1   1   1]
 [  1   2   4]
 [  1   4  16]
 [  1   6  36]
 [  1   8  64]
 [  1  10 100]] 

